export const MATERIAL_ICONS: string[] = [
  // Action
  'accessibility', 'accessibility_new', 'accessible', 'accessible_forward', 'account_balance', 'account_balance_wallet',
  'account_box', 'account_circle', 'add_shopping_cart', 'add_task', 'alarm', 'alarm_add', 'alarm_off', 'alarm_on',
  'all_inbox', 'all_out', 'analytics', 'anchor', 'announcement', 'arrow_right_alt', 'article', 'aspect_ratio',
  'assessment', 'assignment', 'assignment_ind', 'assignment_late', 'assignment_return', 'assignment_returned',
  'assignment_turned_in', 'auto_awesome', 'auto_stories', 'backup', 'backup_table', 'balance', 'batch_prediction',
  'book', 'book_online', 'bookmark', 'bookmark_add', 'bookmark_added', 'bookmark_border', 'bookmark_remove',
  'bookmarks', 'bug_report', 'build', 'build_circle', 'calculate', 'calendar_today', 'calendar_view_day',
  'calendar_view_month', 'calendar_view_week', 'camera_enhance', 'card_giftcard', 'card_membership',
  'card_travel', 'change_history', 'check_circle', 'check_circle_outline', 'chrome_reader_mode', 'circle',
  'class', 'close_fullscreen', 'code', 'code_off', 'commute', 'compare_arrows', 'compress', 'contact_page',
  'contact_support', 'contacts', 'copyright', 'credit_card', 'credit_card_off', 'dangerous', 'dashboard',
  'dashboard_customize', 'data_exploration', 'data_usage', 'date_range', 'delete', 'delete_forever',
  'delete_outline', 'description', 'disabled_by_default', 'dns', 'domain', 'done', 'done_all', 'done_outline',
  'donut_large', 'donut_small', 'drag_indicator', 'dynamic_form', 'edit', 'edit_off', 'euro_symbol',
  'event', 'event_seat', 'exit_to_app', 'expand', 'explore', 'explore_off', 'extension', 'face',
  'face_retouching_natural', 'fact_check', 'favorite', 'favorite_border', 'feedback', 'file_present',
  'filter_alt', 'filter_alt_off', 'find_in_page', 'find_replace', 'fingerprint', 'fit_screen',
  'flaky', 'flight_land', 'flight_takeoff', 'flip_to_back', 'flip_to_front', 'flutter_dash',
  'free_cancellation', 'g_translate', 'gavel', 'generating_tokens', 'get_app', 'gif', 'gif_box',
  'grade', 'grading', 'group_work', 'heart_broken', 'help', 'help_center', 'help_outline',
  'hide_source', 'highlight_alt', 'highlight_off', 'history', 'history_edu', 'history_toggle_off',
  'home', 'home_work', 'horizontal_split', 'hotel_class', 'http', 'https', 'important_devices',
  'info', 'input', 'integration_instructions', 'inventory', 'inventory_2', 'invert_colors',
  'invert_colors_off', 'javascript', 'join_full', 'join_inner', 'join_left', 'join_right',
  'label', 'label_important', 'label_off', 'language', 'launch', 'leaderboard', 'lightbulb',
  'lightbulb_circle', 'lightbulb_outline', 'line_style', 'line_weight', 'list', 'lock', 'lock_clock',
  'lock_open', 'lock_reset', 'login', 'logout', 'loyalty', 'manage_accounts', 'manage_history',
  'manage_search', 'mark_as_unread', 'maximize', 'mediation', 'minimize', 'model_training',
  'new_label', 'next_plan', 'nightlight_round', 'no_accounts', 'noise_aware', 'note_add',
  'offline_bolt', 'offline_pin', 'on_device_training', 'online_prediction', 'opacity', 'open_in_browser',
  'open_in_full', 'open_in_new', 'open_in_new_off', 'open_with', 'outbound', 'outbox', 'outlet',
  'output', 'pageview', 'pan_tool', 'pan_tool_alt', 'payment', 'payments', 'pending', 'pending_actions',
  'percent', 'perm_camera_mic', 'perm_contact_calendar', 'perm_data_setting', 'perm_device_information',
  'perm_media', 'perm_phone_msg', 'perm_scan_wifi', 'pets', 'picture_in_picture', 'picture_in_picture_alt',
  'pin_end', 'pin_invoke', 'pinch', 'plagiarism', 'play_for_work', 'polymer', 'power_settings_new',
  'predictive_text', 'preview', 'print', 'privacy_tip', 'production_quantity_limits', 'published_with_changes',
  'query_builder', 'question_answer', 'question_mark', 'queue', 'quickreply', 'receipt', 'receipt_long',
  'redeem', 'remove_done', 'remove_shopping_cart', 'reorder', 'repartition', 'report_problem',
  'request_page', 'restore', 'restore_from_trash', 'restore_page', 'rocket', 'rocket_launch', 'room',
  'rounded_corner', 'rowing', 'rule', 'saved_search', 'savings', 'schedule', 'schedule_send',
  'search', 'search_off', 'segment', 'send_and_archive', 'settings', 'settings_accessibility',
  'settings_applications', 'settings_backup_restore', 'settings_bluetooth', 'settings_brightness',
  'settings_cell', 'settings_ethernet', 'settings_input_antenna', 'settings_input_component',
  'settings_input_composite', 'settings_input_hdmi', 'settings_input_svideo', 'settings_overscan',
  'settings_phone', 'settings_power', 'settings_remote', 'settings_system_daydream', 'settings_voice',
  'shield', 'shop', 'shop_2', 'shop_two', 'shopping_bag', 'shopping_basket', 'shopping_cart',
  'shopping_cart_checkout', 'smart_button', 'source', 'space_dashboard', 'splitscreen', 'stars',
  'sticky_note_2', 'store', 'subject', 'subtitles', 'subtitles_off', 'supervised_user_circle',
  'supervisor_account', 'support', 'swap_horiz', 'swap_horizontal_circle', 'swap_vert',
  'swap_vertical_circle', 'swipe', 'swipe_down', 'swipe_down_alt', 'swipe_left', 'swipe_left_alt',
  'swipe_right', 'swipe_right_alt', 'swipe_up', 'swipe_up_alt', 'swipe_vertical', 'system_update_alt',
  'tab', 'tab_unselected', 'table_view', 'task', 'task_alt', 'terminal', 'text_rotate_up',
  'text_rotate_vertical', 'text_rotation_angledown', 'text_rotation_angleup', 'text_rotation_down',
  'text_rotation_none', 'theaters', 'thumb_down', 'thumb_down_alt', 'thumb_down_off_alt', 'thumb_up',
  'thumb_up_alt', 'thumb_up_off_alt', 'thumbs_up_down', 'timeline', 'tips_and_updates', 'title',
  'toc', 'today', 'token', 'toll', 'touch_app', 'tour', 'track_changes', 'translate', 'trending_down',
  'trending_flat', 'trending_up', 'try', 'turned_in', 'turned_in_not', 'unfold_less_double',
  'unfold_more_double', 'unpublished', 'update', 'update_disabled', 'upgrade', 'verified',
  'verified_user', 'vertical_split', 'view_agenda', 'view_array', 'view_carousel', 'view_column',
  'view_comfy', 'view_comfy_alt', 'view_compact', 'view_compact_alt', 'view_cozy', 'view_day',
  'view_headline', 'view_kanban', 'view_list', 'view_module', 'view_quilt', 'view_sidebar',
  'view_stream', 'view_timeline', 'view_week', 'visibility', 'visibility_off', 'voice_over_off',
  'watch_later', 'webhook', 'width_full', 'width_normal', 'width_wide', 'wifi_protected_setup',
  'work', 'work_history', 'work_off', 'work_outline', 'wrap_text', 'youtube_searched_for', 'zoom_in',
  'zoom_out',

  // Alert
  'add_alert', 'auto_delete', 'error', 'error_outline', 'notification_important', 'warning', 'warning_amber',

  // AV / Media
  'add_to_queue', 'airplay', 'album', 'art_track', 'audio_file', 'av_timer', 'branding_watermark',
  'call_to_action', 'closed_caption', 'closed_caption_disabled', 'closed_caption_off', 'control_camera',
  'equalizer', 'explicit', 'fast_forward', 'fast_rewind', 'featured_play_list', 'featured_video',
  'fiber_dvr', 'fiber_manual_record', 'fiber_new', 'fiber_pin', 'fiber_smart_record', 'forward_10',
  'forward_30', 'forward_5', 'games', 'hd', 'hearing', 'hearing_disabled', 'high_quality',
  'interpreter_mode', 'library_add', 'library_add_check', 'library_books', 'library_music', 'loop',
  'mic', 'mic_none', 'mic_off', 'missed_video_call', 'movie', 'music_video', 'new_releases', 'not_interested',
  'note', 'pause', 'pause_circle', 'pause_circle_filled', 'pause_circle_outline', 'play_arrow',
  'play_circle', 'play_circle_filled', 'play_circle_outline', 'play_disabled', 'playlist_add',
  'playlist_add_check', 'playlist_add_check_circle', 'playlist_add_circle', 'playlist_play', 'playlist_remove',
  'queue_music', 'queue_play_next', 'radio', 'recent_actors', 'remove_from_queue', 'repeat', 'repeat_on',
  'repeat_one', 'repeat_one_on', 'replay', 'replay_10', 'replay_30', 'replay_5', 'replay_circle_filled',
  'sd', 'shuffle', 'shuffle_on', 'skip_next', 'skip_previous', 'slow_motion_video', 'snooze', 'sort_by_alpha',
  'speed', 'stop', 'stop_circle', 'subscriptions', 'subtitles', 'surround_sound', 'video_call', 'video_file',
  'video_label', 'video_library', 'video_settings', 'videocam', 'videocam_off', 'volume_down',
  'volume_down_alt', 'volume_mute', 'volume_off', 'volume_up', 'web', 'web_asset', 'web_asset_off',

  // Communication
  'add_ic_call', 'app_registration', 'business', 'call', 'call_end', 'call_made', 'call_merge',
  'call_missed', 'call_missed_outgoing', 'call_received', 'call_split', 'cancel_presentation',
  'cell_tower', 'cell_wifi', 'chat', 'chat_bubble', 'chat_bubble_outline', 'clear_all', 'co_present',
  'comment', 'comment_bank', 'contact_emergency', 'contact_mail', 'contact_phone', 'contacts',
  'desktop_access_disabled', 'dialer_sip', 'dialpad', 'document_scanner', 'domain_disabled',
  'domain_verification', 'duo', 'email', 'forum', 'forward_to_inbox', 'hourglass_bottom',
  'hourglass_empty', 'hourglass_full', 'hourglass_top', 'hub', 'import_contacts', 'import_export',
  'invert_colors_on', 'key', 'key_off', 'list_alt', 'live_help', 'location_off', 'location_on',
  'mail_lock', 'mail_outline', 'mark_chat_read', 'mark_chat_unread', 'mark_email_read', 'mark_email_unread',
  'mark_unread_chat_alt', 'message', 'mobile_screen_share', 'more_time', 'nat', 'no_sim', 'pause_presentation',
  'person_add_disabled', 'phone', 'phone_disabled', 'phone_enabled', 'phonelink_erase', 'phonelink_lock',
  'phonelink_ring', 'phonelink_setup', 'portable_wifi_off', 'present_to_all', 'print_disabled',
  'qr_code', 'qr_code_2', 'qr_code_scanner', 'read_more', 'ring_volume', 'rss_feed', 'screen_share',
  'send', 'sentiment_satisfied_alt', 'sip', 'speaker_phone', 'spoke', 'stay_current_landscape',
  'stay_current_portrait', 'stay_primary_landscape', 'stay_primary_portrait', 'stop_screen_share',
  'swap_calls', 'textsms', 'unsubscribe', 'voicemail', 'vpn_key', 'vpn_key_off', 'wifi_calling',
  'wifi_calling_3', 'wifi_tethering', 'wifi_tethering_error', 'wifi_tethering_off',

  // Content
  'add', 'add_box', 'add_circle', 'add_circle_outline', 'add_link', 'archive', 'attribution', 'backspace',
  'ballot', 'biotech', 'block', 'bold', 'calculate', 'clear', 'content_copy', 'content_cut', 'content_paste',
  'content_paste_go', 'content_paste_off', 'content_paste_search', 'copy_all', 'create', 'delete_sweep',
  'deselect', 'drafts', 'dynamic_feed', 'file_copy', 'filter_list', 'filter_list_off', 'flag', 'flag_circle',
  'font_download', 'font_download_off', 'forward', 'gesture', 'how_to_reg', 'how_to_vote', 'inbox',
  'link', 'link_off', 'low_priority', 'mail', 'markunread', 'move_to_inbox', 'next_week', 'outlined_flag',
  'push_pin', 'redo', 'remove', 'remove_circle', 'remove_circle_outline', 'reply', 'reply_all',
  'report', 'report_gmailerrorred', 'report_off', 'save', 'save_alt', 'save_as', 'select_all',
  'send', 'shield', 'sort', 'square_foot', 'stacked_bar_chart', 'stream', 'strikethrough_s', 'tag',
  'text_format', 'undo', 'unarchive', 'upcoming', 'web_stories', 'weekend',

  // Device
  'access_alarms', 'access_time', 'access_time_filled', 'ad_units', 'add_alarm', 'add_to_home_screen',
  'airplanemode_active', 'airplanemode_inactive', 'battery_0_bar', 'battery_1_bar', 'battery_2_bar',
  'battery_3_bar', 'battery_4_bar', 'battery_5_bar', 'battery_6_bar', 'battery_alert', 'battery_charging_full',
  'battery_full', 'battery_saver', 'battery_std', 'battery_unknown', 'bluetooth', 'bluetooth_connected',
  'bluetooth_disabled', 'bluetooth_drive', 'bluetooth_searching', 'brightness_auto', 'brightness_high',
  'brightness_low', 'brightness_medium', 'cable', 'cameraswitch', 'data_saver_off', 'data_saver_on',
  'data_usage', 'developer_mode', 'devices', 'devices_fold', 'do_disturb', 'do_disturb_alt', 'do_disturb_off',
  'do_disturb_on', 'do_not_disturb', 'do_not_disturb_alt', 'do_not_disturb_off', 'do_not_disturb_on',
  'do_not_disturb_on_total_silence', 'dvr', 'edgesensor_high', 'edgesensor_low', 'flashlight_off',
  'flashlight_on', 'flip', 'flourescent', 'fmd_bad', 'fmd_good', 'gamepad', 'gps_fixed', 'gps_not_fixed',
  'gps_off', 'graphic_eq', 'grid_3x3', 'grid_4x4', 'grid_goldenratio', 'hdr_auto', 'hdr_auto_select',
  'hdr_off_select', 'hdr_on_select', 'hdr_plus', 'hdr_strong', 'hdr_weak', 'headphones', 'headphones_battery',
  'headset', 'headset_mic', 'headset_off', 'install_desktop', 'install_mobile', 'keyboard',
  'keyboard_alt', 'keyboard_arrow_down', 'keyboard_arrow_left', 'keyboard_arrow_right', 'keyboard_arrow_up',
  'keyboard_backspace', 'keyboard_capslock', 'keyboard_command_key', 'keyboard_control_key',
  'keyboard_double_arrow_down', 'keyboard_double_arrow_left', 'keyboard_double_arrow_right',
  'keyboard_double_arrow_up', 'keyboard_hide', 'keyboard_option_key', 'keyboard_return', 'keyboard_tab',
  'keyboard_voice', 'laptop', 'laptop_chromebook', 'laptop_mac', 'laptop_windows', 'light_mode',
  'location_disabled', 'location_searching', 'lock_open', 'login', 'logout',
  'media_bluetooth_off', 'media_bluetooth_on', 'memory', 'mobile_friendly', 'mobile_off', 'mobiledata_off',
  'mode_night', 'mode_standby', 'monitor', 'monitor_heart', 'monitor_weight', 'more', 'multitrack_audio',
  'nearby_error', 'nearby_off', 'network_cell', 'network_wifi', 'network_wifi_1_bar', 'network_wifi_2_bar',
  'network_wifi_3_bar', 'night_sight_auto', 'no_encryption', 'no_encryption_gmailerrorred', 'note_alt',
  'password', 'pattern', 'pause_circle_filled', 'phone_android', 'phone_iphone', 'phonelink',
  'phonelink_off', 'photo_camera_back', 'photo_camera_front', 'pin', 'play_lesson', 'price_change',
  'price_check', 'publish', 'remember_me', 'reset_tv', 'restart_alt', 'reviews', 'rsvp', 'scanner',
  'screen_lock_landscape', 'screen_lock_portrait', 'screen_lock_rotation', 'screen_rotation',
  'screen_rotation_alt', 'screen_search_desktop', 'screenshot', 'screenshot_monitor', 'security_update',
  'security_update_good', 'security_update_warning', 'sell', 'send_to_mobile', 'settings_suggest',
  'settings_system_daydream', 'share_location', 'signal_cellular_0_bar', 'signal_cellular_4_bar',
  'signal_cellular_alt', 'signal_cellular_alt_1_bar', 'signal_cellular_alt_2_bar',
  'signal_cellular_connected_no_internet_0_bar', 'signal_cellular_connected_no_internet_4_bar',
  'signal_cellular_no_sim', 'signal_cellular_nodata', 'signal_cellular_null', 'signal_cellular_off',
  'signal_wifi_0_bar', 'signal_wifi_4_bar', 'signal_wifi_4_bar_lock', 'signal_wifi_bad', 'signal_wifi_connected_no_internet_4',
  'sim_card', 'sim_card_alert', 'sim_card_download', 'smartphone', 'speaker', 'speaker_group',
  'splitscreen', 'start', 'storage', 'storm', 'tablet', 'tablet_android', 'tablet_mac', 'thermostat',
  'timer_10_select', 'timer_3_select', 'tv', 'tv_off', 'usb', 'usb_off', 'vibration', 'video_stable',
  'watch', 'watch_off', 'wifi', 'wifi_1_bar', 'wifi_2_bar', 'wifi_lock', 'wifi_off', 'wifi_password',

  // Editor
  'add_chart', 'add_comment', 'align_horizontal_center', 'align_horizontal_left', 'align_horizontal_right',
  'align_vertical_bottom', 'align_vertical_center', 'align_vertical_top', 'area_chart', 'attach_file',
  'attach_money', 'auto_fix_high', 'auto_fix_normal', 'auto_fix_off', 'auto_graph', 'bar_chart',
  'border_all', 'border_bottom', 'border_clear', 'border_color', 'border_horizontal', 'border_inner',
  'border_left', 'border_outer', 'border_right', 'border_style', 'border_top', 'border_vertical',
  'bubble_chart', 'candlestick_chart', 'check', 'checklist', 'checklist_rtl', 'color_lens',
  'colored_lens', 'currency_bitcoin', 'currency_exchange', 'currency_franc', 'currency_lira',
  'currency_pound', 'currency_ruble', 'currency_rupee', 'currency_yen', 'cursor_pointer',
  'data_array', 'data_object', 'difference', 'disabled_visible', 'drag_handle', 'draw',
  'edit_attributes', 'edit_calendar', 'edit_document', 'edit_location', 'edit_location_alt',
  'edit_note', 'edit_notifications', 'edit_road', 'edit_square', 'euro', 'expand_less', 'expand_more',
  'explicit', 'filter_1', 'filter_2', 'filter_3', 'filter_4', 'filter_5', 'filter_6', 'filter_7',
  'filter_8', 'filter_9', 'filter_9_plus', 'format_align_center', 'format_align_justify',
  'format_align_left', 'format_align_right', 'format_bold', 'format_clear', 'format_color_fill',
  'format_color_reset', 'format_color_text', 'format_indent_decrease', 'format_indent_increase',
  'format_italic', 'format_line_spacing', 'format_list_bulleted', 'format_list_bulleted_add',
  'format_list_numbered', 'format_list_numbered_rtl', 'format_overline', 'format_paint',
  'format_quote', 'format_shapes', 'format_size', 'format_strikethrough', 'format_textdirection_l_to_r',
  'format_textdirection_r_to_l', 'format_underlined', 'functions', 'height', 'hexagon',
  'highlight', 'horizontal_distribute', 'horizontal_rule', 'image_search', 'insert_chart',
  'insert_chart_outlined', 'insert_comment', 'insert_drive_file', 'insert_emoticon', 'insert_invitation',
  'insert_link', 'insert_page_break', 'insert_photo', 'line_axis', 'linear_scale', 'list_alt_add',
  'margin', 'merge_type', 'mode', 'mode_comment', 'mode_edit', 'mode_edit_outline', 'monetization_on',
  'money_off', 'money_off_csred', 'move_down', 'move_up', 'multiline_chart', 'notes', 'numbers',
  'padding', 'pentagon', 'pie_chart', 'pie_chart_outline', 'polyline', 'post_add', 'publish',
  'query_stats', 'rounded_corner', 'scatter_plot', 'score', 'share', 'short_text', 'show_chart',
  'space_bar', 'spellcheck', 'square', 'stacked_line_chart', 'star_rate', 'strikethrough_s',
  'subscript', 'superscript', 'table_chart', 'table_rows', 'text_decrease', 'text_fields',
  'text_increase', 'type_specimen', 'vertical_align_bottom', 'vertical_align_center',
  'vertical_align_top', 'vertical_distribute', 'wrap_text',

  // File
  'approval', 'attach_email', 'attachment', 'cloud', 'cloud_circle', 'cloud_done', 'cloud_download',
  'cloud_off', 'cloud_queue', 'cloud_sync', 'cloud_upload', 'compress', 'create_new_folder',
  'difference', 'download', 'download_done', 'download_for_offline', 'downloading',
  'drive_file_move', 'drive_file_move_rtl', 'drive_file_rename_outline', 'drive_folder_upload',
  'expand', 'file_download', 'file_download_done', 'file_download_off', 'file_open', 'file_upload',
  'file_upload_off', 'folder', 'folder_copy', 'folder_delete', 'folder_off', 'folder_open',
  'folder_shared', 'folder_zip', 'format_overline', 'grid_view', 'merge', 'open_with',
  'request_quote', 'rule_folder', 'snippet_folder', 'source', 'splitscreen', 'text_snippet',
  'topic', 'unfold_less', 'unfold_more', 'upload', 'upload_file', 'workspaces', 'workspaces_filled',
  'workspaces_outline',

  // Hardware
  'browser_not_supported', 'browser_updated', 'cast', 'cast_connected', 'cast_for_education',
  'computer', 'connected_tv', 'desktop_mac', 'desktop_windows', 'developer_board',
  'developer_board_off', 'device_hub', 'device_thermostat', 'device_unknown', 'devices_other',
  'dock', 'earbuds', 'earbuds_battery', 'fitness_center',
  'headphones', 'headphones_battery', 'headset', 'headset_mic', 'headset_off', 'home_max',
  'home_mini', 'keyboard', 'keyboard_alt', 'keyboard_voice', 'laptop', 'memory', 'monitor',
  'mouse', 'network_check', 'phone_android', 'phone_iphone', 'phonelink', 'phonelink_off',
  'point_of_sale', 'power', 'power_input', 'router', 'scanner', 'security', 'sim_card',
  'smartphone', 'speaker', 'speaker_group', 'start', 'storage', 'tablet', 'tablet_android',
  'tablet_mac', 'toys', 'tv', 'videogame_asset', 'videogame_asset_off', 'watch',

  // Home / Devices & IoT
  'air', 'bathroom', 'bathtub', 'bed', 'bedroom_baby', 'bedroom_child', 'bedroom_parent',
  'blender', 'chair', 'chair_alt', 'chandelier', 'coffee', 'coffee_maker', 'countertops',
  'curtains', 'curtains_closed', 'desk', 'dining', 'dishwasher_gen', 'door_back', 'door_front',
  'door_sliding', 'doorbell', 'dry', 'electrical_services', 'energy_savings_leaf', 'faucet',
  'fireplace', 'flatware', 'garage', 'grass', 'heat_pump', 'home_iot_device', 'hot_tub',
  'house', 'house_siding', 'iron', 'kitchen', 'light', 'light_mode', 'living', 'manage_search',
  'microwave', 'mode_fan_off', 'mop', 'outlet', 'podcasts', 'range_hood', 'refrigerator',
  'roofing', 'room_preferences', 'room_service', 'sensor_door', 'sensor_occupied',
  'sensor_window', 'shower', 'soap', 'solar_power', 'spa', 'speaker', 'sprinkler',
  'table_bar', 'table_restaurant', 'tv', 'vacuum', 'wash', 'water_damage', 'water_drop',
  'window', 'wine_bar', 'yard',

  // Maps / Location
  'add_home', 'add_home_work', 'add_location', 'add_location_alt', 'add_road', 'agriculture',
  'airline_stops', 'airlines', 'airport_shuttle', 'atm', 'attractions', 'badge', 'bakery_dining',
  'beenhere', 'bike_scooter', 'breakfast_dining', 'brunch_dining', 'bus_alert', 'car_crash',
  'car_rental', 'car_repair', 'castle', 'category', 'celebration', 'church', 'cinema',
  'cleaning_services', 'compass_calibration', 'connecting_airports', 'crisis_alert', 'delivery_dining',
  'departure_board', 'design_services', 'dining', 'directions', 'directions_bike', 'directions_boat',
  'directions_boat_filled', 'directions_bus', 'directions_bus_filled', 'directions_car',
  'directions_car_filled', 'directions_ferry', 'directions_off', 'directions_railway',
  'directions_railway_filled', 'directions_run', 'directions_subway', 'directions_subway_filled',
  'directions_transit', 'directions_transit_filled', 'directions_walk', 'dry_cleaning', 'edit_location',
  'edit_location_alt', 'edit_road', 'egg', 'egg_alt', 'electric_bike', 'electric_bolt', 'electric_car',
  'electric_moped', 'electric_rickshaw', 'electric_scooter', 'electrical_services',
  'emergency', 'emergency_recording', 'emergency_share', 'ev_station', 'factory', 'fastfood',
  'fence', 'flight', 'fort', 'free_breakfast', 'hail', 'handy_craftsman', 'hardware',
  'hiking', 'home_work', 'hotel', 'hvac', 'icecream', 'kebab_dining', 'layers', 'layers_clear',
  'leafy_bug', 'library_books', 'liquor', 'local_activity', 'local_airport', 'local_atm',
  'local_bar', 'local_cafe', 'local_car_wash', 'local_convenience_store', 'local_dining',
  'local_drink', 'local_fire_department', 'local_florist', 'local_gas_station', 'local_grocery_store',
  'local_hospital', 'local_hotel', 'local_laundry_service', 'local_library', 'local_mall',
  'local_movies', 'local_offer', 'local_parking', 'local_pharmacy', 'local_phone', 'local_pizza',
  'local_play', 'local_police', 'local_post_office', 'local_printshop', 'local_see', 'local_shipping',
  'local_taxi', 'location_city', 'location_on', 'location_pin', 'location_searching',
  'lunch_dining', 'map', 'maps_home_work', 'maps_ugc', 'medical_services', 'menu_book',
  'merge', 'military_tech', 'minor_crash', 'miscellaneous_services', 'money', 'moped',
  'mosque', 'moving', 'museum', 'my_location', 'navigation', 'near_me', 'near_me_disabled',
  'nightlife', 'no_meals', 'no_transfer', 'not_listed_location', 'park', 'pedal_bike',
  'person_pin', 'person_pin_circle', 'pest_control', 'pest_control_rodent', 'pharmacy_cross',
  'pin_drop', 'place', 'playground', 'police', 'pool', 'post_add', 'ramen_dining',
  'rate_review', 'rice_bowl', 'roundabout_left', 'roundabout_right', 'route', 'run_circle',
  'safety_check', 'sailing', 'satellite_alt', 'set_meal', 'signpost', 'skateboarding',
  'sledding', 'snowboarding', 'snowmobile', 'snowshoeing', 'sports_bar', 'stadium',
  'store_mall_directory', 'streetview', 'subway', 'synagogue', 'tapas', 'taxi_alert',
  'temple_buddhist', 'temple_hindu', 'terrain', 'theater_comedy', 'tire_repair',
  'traffic', 'train', 'tram', 'transfer_within_a_station', 'transit_enterexit', 'trip_origin',
  'turn_left', 'turn_right', 'turn_sharp_left', 'turn_sharp_right', 'turn_slight_left',
  'turn_slight_right', 'two_wheeler', 'u_turn_left', 'u_turn_right', 'umbrella', 'villa',
  'volunteer_activism', 'warehouse', 'water', 'wine_bar', 'wrong_location', 'zoo',

  // Navigation
  'apps', 'apps_outage', 'arrow_back', 'arrow_back_ios', 'arrow_back_ios_new', 'arrow_downward',
  'arrow_drop_down', 'arrow_drop_down_circle', 'arrow_drop_up', 'arrow_forward', 'arrow_forward_ios',
  'arrow_left', 'arrow_right', 'arrow_upward', 'cancel', 'check', 'chevron_left', 'chevron_right',
  'close', 'double_arrow', 'east', 'expand_less', 'expand_more', 'first_page', 'fullscreen',
  'fullscreen_exit', 'home', 'home_filled', 'last_page', 'menu', 'menu_open', 'more_horiz',
  'more_vert', 'navigate_before', 'navigate_next', 'north', 'north_east', 'north_west', 'refresh',
  'south', 'south_east', 'south_west', 'subdirectory_arrow_left', 'subdirectory_arrow_right',
  'unfold_less', 'unfold_more', 'west',

  // Notification
  'account_tree', 'adb', 'airline_seat_flat', 'airline_seat_flat_angled', 'airline_seat_individual_suite',
  'airline_seat_legroom_extra', 'airline_seat_legroom_normal', 'airline_seat_legroom_reduced',
  'airline_seat_recline_extra', 'airline_seat_recline_normal', 'confirmation_number', 'directions_off',
  'disc_full', 'do_disturb', 'do_disturb_alt', 'do_disturb_off', 'do_disturb_on', 'do_not_disturb',
  'do_not_disturb_alt', 'do_not_disturb_off', 'do_not_disturb_on', 'drive_eta', 'enhanced_encryption',
  'event_available', 'event_busy', 'event_note', 'folder_special', 'imagesearch_roller', 'live_tv',
  'mms', 'more', 'network_check', 'network_locked', 'network_wifi', 'no_encryption', 'phone_bluetooth_speaker',
  'phone_callback', 'phone_forwarded', 'phone_in_talk', 'phone_locked', 'phone_missed', 'phone_paused',
  'power', 'running_with_errors', 'sd_card', 'sd_card_alert', 'sim_card_alert', 'sms', 'sms_failed',
  'support_agent', 'sync_disabled', 'sync_lock', 'sync_problem', 'system_update', 'tap_and_play',
  'time_to_leave', 'tv', 'vibration', 'voice_chat', 'vpn_lock', 'wc', 'wifi', 'wifi_off',

  // Places
  'ac_unit', 'airport_shuttle', 'all_inclusive', 'beach_access', 'business_center', 'casino',
  'child_care', 'child_friendly', 'fitness_center', 'free_breakfast', 'golf_course', 'hot_tub',
  'kitchen', 'meeting_room', 'no_meeting_room', 'people', 'pool', 'room_service',
  'smoke_free', 'smoking_rooms', 'spa', 'sports_bar', 'yacht_lake',

  // Science
  'air', 'biotech', 'cast', 'connected_tv', 'coronavirus', 'co2', 'colorize', 'compost',
  'device_thermostat', 'energy_savings_leaf', 'filter_drama', 'flood', 'forest', 'grain',
  'healing', 'heat_pump', 'invert_colors', 'lan', 'landslide', 'light_mode', 'mode_night',
  'mode_standby', 'monitor_heart', 'nature', 'nature_people', 'ophthalmology', 'phishing',
  'psychology', 'psychology_alt', 'public', 'public_off', 'radar', 'recycling', 'reduce_capacity',
  'sanitizer', 'science', 'severe_cold', 'solar_power', 'storm', 'thunderstorm', 'tornado',
  'tsunami', 'umbrella', 'vaccines', 'volcano', 'water', 'wb_cloudy', 'wb_shade', 'wb_sunny',
  'wb_twilight', 'wind_power',

  // Social
  'cake', 'celebration', 'circle', 'connect_without_contact', 'construction', 'coronavirus',
  'cruelty_free', 'deck', 'default_offline', 'domain', 'edit_notifications', 'elderly',
  'elderly_woman', 'emoji_emotions', 'emoji_events', 'emoji_flags', 'emoji_food_beverage',
  'emoji_nature', 'emoji_objects', 'emoji_people', 'emoji_symbols', 'emoji_transportation',
  'engineering', 'face', 'face_2', 'face_3', 'face_4', 'face_5', 'face_6', 'family_restroom',
  'female', 'fireplace', 'follow_the_signs', 'food_bank', 'front_hand', 'group',
  'group_add', 'group_off', 'group_remove', 'groups', 'groups_2', 'groups_3', 'handshake',
  'health_and_safety', 'heart_broken', 'hiking', 'history_edu', 'home', 'html', 'interests',
  'ios_share', 'kayaking', 'king_bed', 'kitesurfing', 'location_city', 'luggage', 'male',
  'man', 'man_2', 'man_3', 'man_4', 'medical_information', 'military_tech', 'mood',
  'mood_bad', 'nights_stay', 'no_luggage', 'nordic_walking', 'notifications', 'notifications_active',
  'notifications_none', 'notifications_off', 'notifications_paused', 'outdoor_grill',
  'pages', 'paragliding', 'party_mode', 'people', 'people_alt', 'people_outline', 'person',
  'person_2', 'person_3', 'person_4', 'person_add', 'person_add_alt', 'person_add_alt_1',
  'person_off', 'person_outline', 'person_remove', 'person_remove_alt_1', 'person_search',
  'piano', 'piano_off', 'plus_one', 'poll', 'precision_manufacturing', 'psychology',
  'public', 'recommend', 'reduce_capacity', 'roller_skating', 'roofing', 'rowing',
  'running_with_errors', 'sanitizer', 'school', 'science', 'self_improvement', 'sentiment_dissatisfied',
  'sentiment_neutral', 'sentiment_satisfied', 'sentiment_very_dissatisfied', 'sentiment_very_satisfied',
  'share', 'sign_language', 'single_bed', 'skateboarding', 'sledding', 'snowboarding',
  'snowshoeing', 'social_distance', 'sports', 'sports_baseball', 'sports_basketball',
  'sports_cricket', 'sports_esports', 'sports_football', 'sports_golf', 'sports_gymnastics',
  'sports_handball', 'sports_hockey', 'sports_kabaddi', 'sports_martial_arts', 'sports_mma',
  'sports_motorsports', 'sports_rugby', 'sports_score', 'sports_soccer', 'sports_swimming',
  'sports_tennis', 'sports_volleyball', 'surfing', 'temple_buddhist', 'temple_hindu',
  'thumb_down', 'thumb_down_alt', 'thumb_up', 'thumb_up_alt', 'thumbs_up_down', 'transgender',
  'travel_explore', 'vaccines', 'waving_hand', 'whatshot', 'wheelchair_pickup', 'woman',
  'woman_2', 'connect_without_contact',

  // Toggle
  'check_box', 'check_box_outline_blank', 'indeterminate_check_box', 'radio_button_checked',
  'radio_button_unchecked', 'star', 'star_border', 'star_border_purple500', 'star_half',
  'star_outline', 'star_purple500', 'toggle_off', 'toggle_on',

  // Transportation
  'agriculture', 'airline_seat_flat', 'airlines', 'airport_shuttle', 'baby_changing_station',
  'bike_scooter', 'directions_bike', 'directions_boat', 'directions_bus', 'directions_car',
  'directions_railway', 'directions_run', 'directions_subway', 'directions_transit', 'directions_walk',
  'electric_bike', 'electric_car', 'electric_moped', 'electric_rickshaw', 'electric_scooter',
  'ev_station', 'flight', 'flight_land', 'flight_takeoff', 'hail', 'kayaking', 'local_shipping',
  'local_taxi', 'luggage', 'minor_crash', 'moped', 'motorcycle', 'moving', 'no_transfer',
  'pedal_bike', 'rv_hookup', 'sailing', 'scooter', 'skateboarding', 'sledding', 'snowmobile',
  'snowshoeing', 'subway', 'taxi_alert', 'train', 'tram', 'transfer_within_a_station',
  'two_wheeler',

  // Weather
  'ac_unit', 'beach_access', 'brightness_3', 'brightness_4', 'brightness_5', 'brightness_6',
  'brightness_7', 'cloudy_snowing', 'cyclone', 'filter_drama', 'flood', 'foggy', 'grain',
  'hot_tub', 'hurricane', 'landslide', 'light_mode', 'mode_fan_off', 'nights_stay',
  'plus_one', 'severe_cold', 'snowing', 'storm', 'sunny', 'sunny_snowing', 'thermostat',
  'thunderstorm', 'tornado', 'tsunami', 'umbrella', 'volcano', 'wb_cloudy', 'wb_shade',
  'wb_sunny', 'wb_twilight', 'wind_power',
].filter((value, index, self) => self.indexOf(value) === index).sort();
